[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "mongodb"
version = "5.2.2"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "Database", "IT Operations/Databases", "Cost/Freemium", "NoSQL"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "mongodb-native"
version = "5.2.2"
path = "../native/build/libs/mongodb-native-5.2.2.jar"

[[platform.java21.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-sync"
version = "5.1.0"
path = "./lib/mongodb-driver-sync-5.1.0.jar"

[[platform.java21.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-core"
version = "5.1.0"
path = "./lib/mongodb-driver-core-5.1.0.jar"

[[platform.java21.dependency]]
groupId = "org.mongodb"
artifactId = "bson"
version = "5.1.0"
path = "./lib/bson-5.1.0.jar"
