[package]
distribution = "2201.7.0"
org = "ballerinax"
name = "mongodb"
version = "5.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.lib"
artifactId = "mongodb-native"
version = "5.0.0"
path = "../native/build/libs/mongodb-native-5.0.0.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-sync"
version = "4.11.1"
path = "./lib/mongodb-driver-sync-4.11.1.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "mongodb-driver-core"
version = "4.11.1"
path = "./lib/mongodb-driver-core-4.11.1.jar"

[[platform.java17.dependency]]
groupId = "org.mongodb"
artifactId = "bson"
version = "4.11.1"
path = "./lib/bson-4.11.1.jar"
