[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "mongodb"
version = "3.2.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases", "Cost/Freemium"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[[platform.java11.dependency]]
path = "../mongodb-native/build/libs/mongodb-native-3.2.0-all.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "3.2.0"
