[package]
org = "ballerinax"
name = "mongodb"
version = "2.0.3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"


[[platform.java11.dependency]]
path = "../mongo-utils/target/mongo-utils-2.0.3.jar"
groupId = "org.wso2.ei"
artifactId = "mongo-utils"
version = "2.0.3"
