[[dependency]]
org = "ballerina"
name = "crypto"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.1"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-beta.1"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-beta.1"
